version: '3.5'

services:

  caf_importer:
    container_name: caf_importer
    build: .
    volumes:
      - ./import.log:/caf-tr-import/import.log
      - ./tmp:/caf-tr-import/tmp
    environment:
      NODE_OPTIONS: '--max_old_space_size=4096'
      TMP: './tmp'
      TR: 'http://tr_textrepo:8080'
      CACHE: 250
      CAF: ${CAF}
      CAF_INDEX: ${CAF_INDEX}
    networks:
      - test_es
    command: ./import.sh

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: es
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - test_es

networks:
  test_es:
    driver: bridge
