version: '3.1'

services:
  gnb_es:
    image: gnb-elastic:20210111
    ports:
      - "9200:9200"
    networks:
      - gnb_network

  gnb_nginx:
    image: nginx:1.19
    volumes:
      - ./ui:/etc/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/mime.types:/etc/nginx/conf/mime.types
    networks:
      - gnb_network
      - nginxproxynetwork
    environment:
      VIRTUAL_HOST: gnb.tt.di.huc.knaw.nl
    ports:
      - 80:80
    depends_on:
      - gnb_es

networks:
  nginxproxynetwork:
    external:
      name: nginxproxynetwork
  gnb_network:
