import pickle

# Define an empty dictionary for deletions
deletions = {}

pre_deletions = {
r'^ *.? +': '',
r', *$': '',
r'^ *h:\b': '',
r'\.': '',
r',? *$': '',
r'—': '',
r' +': ' ',
r"^ *[,'-]+": '',
r'[@/#=„.:,?!"¬,;:=„]': '',
r"^ *d?e?'?n? *he?e?re?n?": '',
r"^ *d?e?'?n? *he?e?re?n?": '',


    # Add more pre-deletions here
}

# Update the deletions dictionary with pre-deletions
deletions.update(pre_deletions)



# Add each name to the dictionary of deletions with word boundaries around it

#Define the additional deletions dictionary
additional_deletions = {
r'^ *tot *\w*( *[^a-zA-Z]*)?$': '',
r'^ *[0-9]+ \w* *1[5678][0-9]+\b,?( *voor\b|soo?\b|verr?e?\b|ooc?k\b|daar\b|b[ijy]+\b)':'',
r'[0-9]': '',
r'jongstled[a-z]*\b': '',
r"^ *d?'?he?e?re?n?\b( *van)?( *tot *\w*)? *$": '',
r"^ *d?'?he?e?re?n?\b *van *\w*\b": '',
r"^ *d?e?n?'?he?e?re?e?n?\b *": '',
r'ber *ke.{0,2}rood\w*':'',
r'\bhonder[dt]+\b':'',
r'\bgulden\w*':'',
r'\w*da[ae]lder\w*':'',
r'\bthans\b': '',
r'^ haare?\b':'',
r'august\w*':'',
r'fe[vb]rua\w*':'',
r'\bbe[ijy]+den?\b':'',
r'gevolgt was':'',
r'geweldige\w*':'',
r'\bge[sz]wo+r\w*':'',
r'\bgewe+[sz]e\w*':'',
r'\bin *z[ijy]+ne?n? *lee?[vf]e\w*':'',
r'\bgevoe[chg][dt]\b':'',
r'\bhal[fve]+\b':'',
r'^ *haa?re?n?s?\b':'',
r'\bhebbende\b':'',
r'\bhee?e(f+t?)?\b':'',
r'\bverklaar[dt]+\b':'',
r'van *(zyne|den)? *$': '',
r'pr[ae]*sentibus': '',
r'\bw(ij|y)len\b': '',
r'\bhrij\b': '',
r'\bh\.\b': '',
r'[$=+!@#%^&]': '',
r'^ *het\b': '',
r'\baan *$': '',
r',? *\bgesubstitueerde *$': '',
r'\bjacob\b': '',
r'\bjo?h?an\b': '',
r'^ *gewe?esen *': '',
r'^nant\b': '',
r'\bby *$': '',
r'\b(wel|hooc?h?g?s?t?)ge[dm]\w*\b': '',
r'\b(met|van|als|tot)\b *$': '',
r'^ *van *der *$': '',
r',? +(de *|en *|jz *)* *$': '',
r'[jt]egenwo\w*': '',
r'\ben\b *$': '',
r'(de)? *voornoemden?\b': '',
r'^ *(plle|marcus)\b': '',
r',? *(van|voor) *$': '',
r'\ben\b *$': '',
r'^ *\ben\b': '',
r'\b(in *zyne? lee?ven|gewee?sen)+': '',
r'\b(meerge|voor)noemde\b': '',
r'\bvoor[nsztd]+(chre[vy]e)?.?\b': '',
r'\b(meer)?gemel[dt]e\b': '',
r'\brespecti[uv]e\b': '',
r'^ +| +$': '',
r'^[^a-zA-Z]+': '',
r'^ *heere?n?\b': '',
r'\bhoogh?gem[a-z]*': '',
r'\bby *den? *$': '',
r'\bde[rns]? *$': '',
r'\bte *$': '',
r'\bhooc?g?h?s?t?ged[a-z]*\b': '',
r'^ *zyne?\b *': '',
r'^ *den\b *': '',
r'\ben *$': '',
r'^van\b *(den)? *': '',
r'^ *[bh]y\b *': '',
r'\bgewee?s\w*': '',
r'\boverlede?en\w*': '',
r'\bdessel[fv][a-z]ss*\b': '',
r'wel *geboo?ren': '',
r'\bvan *(het|de)? *$': '',
r'\bdes?sel[uvf]e?s?\b': '',
r'aldaar': '',
r'^ *de[nsr] *sel[fv][a-z]*\b': '',
r'\booc?k\b': '',
r'\bgelyk\b': '',
r'\bhy\b': '',
r'^ *eerste\b': '',
r'\balda[ae]r\b': '',
r'vandien *$': '',
r'\bin *(het *)?$': '',
r'^ *\bde[rsn]?\b': '',
r'\bmee?de\b': '',
r'^(zijn\b *|als\b *|van\b *|ook\b *|bij\b *)*': '',
r"^ *\b(en\b|de\b|die\b|d'\b)": '',
r"\b(en\b|de\b|die\b|d'\b )\b *$": '',
r'tot *[a-z]* *$': '',
r'^ *(den|alle|twee|anderen?)\b': '',
r'\balhier\b': '',
r'\beerbaa?r[a-z]*\b': '',
r'\beer(der|tyd\w*)\b': '',
r'^ *de[nrs]?\b': '',
r'^ *hy\b': '',
r'\bee?nige\b': '',
r'(voor *)? sig *sel[fv][a-z]*\b': '',
r'voor soo \w*\b( *daar)?': '',
r'^ *in *[kq][wuv]alit.*als\b': '',
r'^ *in *(z[ijy]+n\w*)? *lee?v\w*': '',
r'\bwel *gebo.{0,3}en': '',
r'\bbevo?or\w*': '',
r'\boverle\w*': '',
r'^ *\b(dat\b *|daar\b *|voor\b *|niet\b *|nu\b *|by\b *|alsoo?\b *|toe\b *|b[ijy]+\b *|niets?\b *|aan\b *| het\b *|to\b *|sy\b *|dan\b *)+\b': '',
r'^ *.? +': '',
r',? *$': '',
r'^ *h:\b': '',
r'\.': '',
r'—': '',
r' +': ' ',
r"^ *[,'-]+": '',
r'[@/#=„.:,?!"¬,;:=„]': '',
r"^ *de?n?'?\bhe?e?re?n?\b *van\b *[a-z]*\b *(en\b *)?(van\b *)?(\w*)? *$": '',
r'^ *[0-9]+ [a-z]+\b *1[5678][0-9][0-9]\b *(b[yij]+)?$': '',
r'^ *.? +': '',
r', *$': '',
r'^ *h:\b': '',
r'\.': '',
r',? *$': '',
r'—': '',
r' +': ' ',
r"^ *[,'-]+": ' ',
r'\bb[ijy]* *$':'',
r'^ *\b(ooc?k\b *|alvoo?r\w*\b *|soo?\b *|veel\b *|geene?\b *|die\b *|si[chg]+\b *|t[yij]+d\b *|toe\b *|niet\b *|tot\b *|b[yij]+\b *|voor\b *|dat\b *|daar\b *|nu\b *|alsoo\b *|sy\b *|daar\b *|toe\b *|als\b *|dan\b *|niets\b *|sullen\b *|. +|no[chg]+\b *|aan\b *|als\b *|niet\b *|dan\b *|o[uv]er\b *|n[au]+\b *|vergeefs\b *|sal\b *|te\b *|nu\b *|gee?ne\b *|het\b *|tot\b *|sy\b *|dan\b *|weini[chg]+\b)*\b *':'',
r'^ *.? +': '',
r', *$': '',
r'^ *h:\b': '',
r'\.': '',
r',? *$': '',
r'—': ' ',
r' +': ' ',
r"^ *[,'-]+": '',
r'\bb[ijy]* *$':'',
r'\bbruin\w*': '',
r'\bvan st[ae]rr\w*b[uo]\w*': '',
r'\b[zl]e.t.{0,8}v\w*n': '',
r'\bvan [sz]waa?nen?bur\w*': '',
r'\bb.{0,2}rken *r\w*': '',
r'\b[sz]eec?ker\w*':'',
r'\bzoo?\b':'',
r'\bhamel': '',
r'^ *[sz][ijy]+n?d?e\b':'',
r'\blyn *den': '',
r'\bwegen\b':'',
r'\bheems *k\w*':'',
r'\bbrantsen': '',
r'\bvan *blit\w*': '',
r'^ *o+\b':'',
r'\bagter\b':'',
r'\balleen\b':'',
r'\bbe(voe[chg]+[dt]|wee?[zs]en)\b':'',
r'\bbye\b':'',
r'\bv[ijy]+f+(ti[chg]+)?\b':'',
r'\bint\b *$':'',
r'\bburg\b *$':'',
r'\b(drie *|[zs]esti[chg]+ *|veertig *|agt *|dui[sz]en[dt]+ *|twee *|ee?nige? *|hendri\w* *|lu[ck]as *)\b':'',
r'^ *a+nd[dtne]*\b':'',
r"^ *d?e?n?'?\bhe?e?re?e?n?\b *": '',
r'\ba[ae]ng[ae]+(nde|[vu]en|stel|nom|schre|[zs]ie)\w*':'',
r'\bachterwee?s\w*':'',
r'\bhem *men': '',
r'cornelis *\w*':'',
r'\bsub\b *$':'',
r'^ *h?e? *e?e? *r?e?n? *(van *)*( *en *)*( *ander\w* *)?$': '',
r'^ *.{0,2} *$':'',
r'\bmaa[rn][td]\b': '',
r'\boct\w*': '',
r'\bju[ln][iye]+\b': '',
r'\bsij\b':'',
r'^ *\b(ooc?k\b *|we+gens?\b *|le+di[chg]+\b *|wel\b *|he+re?n?\b *|alsdan\b *|genomen\b *|in\b *|het\b *|daar\b *|b[eijy]+den?\b *|vier\b *|twintig\b *|en\b *|hebben\b *|aanwe+[sz]en\w*\b *|alles\b *|[sz]ij\b *|nu\b *|sulc?k?x?s?\b *|als\b *|dan\b *|ge[sz]ien\b *|gel[ijy]+c?k\b *|nog\b *|over\b *|alvoo?r\w*\b *|was\b *|veel\b *|welke?\b *|sy\b *|om\b *|die\b *|dat\b *|gemelden?\b *|door\b *|soo?\b *|haare?n?\b *|veel\b *|dag\b *|sy\b *|geene?\b *|onse\b *|[iyj]eder?\b *|blokje\b *|voorschr\w*\b *|die\b *|si[chg]+\b *|t[yij]+d\b *|toe\b *|niet\b *|tot\b *|b[yij]+\b *|voor\b *|dat\b *|daar\b *|nu\b *|alsoo\b *|sy\b *|daar\b *|toe\b *|als\b *|dan\b *|niets\b *|sullen\b *|.\b *|no[chg]+\b *|aan\b *|als\b *|niet\b *|dan\b *|o[uv]er\b *|n[au]+\b *|vergeefs\b *|sal\b *|te\b *|nu\b *|gee?ne\b *|het\b *|tot\b *|sy\b *|dan\b *|weini[chg]+\b *)+': '',
r'\bhe+re?n\b *$':'',
r'\bhe+re?n?\b *$':'',
r'\bswa\w*burg\w*':'',
r'\bwan+e+r\b':'',
r'\bsuc+es+i.el\w*':'',
r'\bwe+ke[nl]i?j?c?k?\b':'',
r'\b(de\b *|nu\b *|ha+re?n? *|om\b *|niet\b *|veel *|[sz][ijy]+nd?e?n? *)$':'',

}

# Update the deletions dictionary with the additional deletions
deletions.update(additional_deletions)
