substitutions = {
    r" ' s ": " 's ",
    r" s *' ": " 's ",
    r'': '',
    r' *[-‚Äî] *': '-',
    r'-+': '-',
    r',,?,': ',',
    r' +,': ',',
    r' *\bende\b *': ', ',
    r'^ *.? +': '',
    r', *$': '',
    r'^ *h:\b': '',
    r'\.': '',
    r',? *$': '',
    r'—': '',
    r' +': ' ',
    r"^ *[,'-]+": '',
    r'[@/#=„.:,?!"¬,;:=„]': '',
    r"^ *d?e?'?n? *he?e?re?n?t?o?c?h?g?\b *": '',
    r"^ *d?e?'?n? *he?e?re?n?t?o?c?h?g?\b *": '',
    r" ' +": "'",
    r'den *bosch': "'s hertogenbosch", 
    r'van den lande': "'s lands",
    r'(burger|inwoner|burgemeester) *der stadt': r"'\1 van de stad'",
    r'‚àö¬©': 'é',
    r'‚Äö√†√∂¬¨¬©': 'é',
    r'ae': 'aa',
    r'geschreven':'',
    r'\baen\b': 'aan',
    r"\ba[ae]n *t'?\b": 'aan het',
    r'(a?a|e)rt[sz] *h[ae]rto[a-z]*\b': 'aartshertog',
    r'\bresident':'',
    r'geschreven':'',
    r'gewe+[sz]ene?n?':'',
    r'w[ijy]len':'',
    r'admirael': 'admiraal',
    r'adm[a-z]*r[a-z]*l[a-z]\b': 'admiraal',
    r'admiraliteyt': 'admiraliteit',
    r'adm[a-z]*r[a-z]*l[a-z]*t[a-z]*\b': 'admiraliteit',
    r'advocaet': 'advocaat',
    r'advocaten': 'advocaat',
    r'aff?geson *$': 'affgesonden',
    r'aff?ge[sz]anten?': 'afgezante',
    r'geboo?ren *(te|in|van)\b': 'afkomstig uit',
    r'geboorti(ch|g) (uit|van|in)': 'afkomstig uit',
    r'agent tot [a-z]*\b': 'agent',
    r'\bamm? *anu[a-z]*\b': 'amanuensis',
    r'am *bassadeur': 'ambassadeur',
    r'\bambr[a-z]*\b': 'ambassadeur',
    r'ambassade\b': 'ambassadeur',
    r'ambassadeur *des *koning': 'ambassadeur van de koning',
    r'baclouch': 'bachlouch',
    r'\bbai?l[ij]\w*\b': 'bailliu',
    r'bailliu der stadt': 'bailliu van',
    r'\bd?l?en? *baron': 'baron',
    r'\bbaroe?n?n[ijvy*]?e?n?\b': 'baron',
    r'\bbaron de\b': 'baron van',
    r"\bbaron *d'": 'baron van ',
    r'\bvrouwe *baron?nesse\b': 'baronnesse',
    r'bergen.*zoom\b': 'bergen op zoom',
    r'berkenrode': 'berkenroode',
    r'bewaer': 'bewaar',
    r'bewin[a-z]*bber(en|s)?': 'bewindhebber',
    r'beijeren': 'beyeren',
    r'\bby\b': 'bij',
    r'bondge[ncvr][oc]+[d tr]': 'bondgenoot',
    r'\bbonen\b': 'boonen',
    r'braban[dt]\b': 'brabandt',
    r'\bbran[a-z]*b[ou]r(ch|g)[a-z]*\b': 'brandenburg',
    r'brouc?k?h?\b': 'broeck',
    r'broek': 'broeck',
    r'\bbruijn *nincx': 'bruijnincx',
    r'brui?j?y?ninc?x': 'bruyninx',
    r'burch\b': 'burg',
    r'burgh$': 'burg',
    r'b[uo]rc?k?g?h?\b': 'burg',
    r'b[ou]rger? *meester': 'burgemeester',
    r'\bb[uo]r(ch|g)h?er\b': 'burger',
    r'burger tot?': 'burger van',
    r'\bcaan\b': 'caen',
    r'canonik': 'canonicq',
    r'\b[ck]api?t[a-z]*n\b': 'capiteyn',
    r'\bcat\b': 'cats',
    r'gt': 'cht',
    r'\b(brandenburg.*keurvorst|keurvorst.*brandenburg\b)': 'churfurst van brandenburg',
    r'cheurvorst': 'churvorst',
    r'churvorst *van': 'churvorst van',
    r'churf[a-z]*\b': 'churvorstelijk',
    r'colijer': 'coljer',
    r'collator der': 'collator van de',
    r'\bcoll?onn?el\b': 'collonel',
    r'commande[a-z]*\b': 'commandant',
    r'\bcommaa?n?d(an|eu)[a-z]*\b': 'commandant',
    r'commandant (te|tot)': 'commandant van',
    r'commmandant der stadt': 'commandant van',
    r'commandant der': 'commandant van de',
    r'commandant officier': 'commanderende officier',
    r'commandee?r[a-z]*\b (tot|der stad)': 'commandeur van',
    r'commissarise?n?': 'commissarissen',
    r'\b[cc]ompe?[.]?\b': 'compagnie',
    r'comp[nr]?i?e': 'compagnie',
    r'compaignie': 'compagnie',
    r'consul tot': '',
    r'consul':'',
    r'contr[ae]rolleur': 'controlleur',
    r'conuoy': 'convoy',
    r'czaer': 'czaar',
    r'\bzaarsche': 'czaarsche',
    r"d' *": "d'",
    r'\bde *raaf\b': 'de graaf',
    r"d'hee": 'de hee',
    r'dezaken': 'de zaken',
    r'dee?nn?emar[a-z]*\b': 'denemarken',
    r'den[a-z]*marken': 'denemarken',
    r'der sta\b': 'der stadt',
    r'\bdee?[sz]er? *land[a-z]*\b': 'dezer lande',
    r'\bdoorlu[a-z]*\b': 'doorluchtigheid',
    r'\bdl?t\b': 'doorluchtigheid',
    r'doorlt\b': 'doorluchtigheid',
    r'drie.*geest.*[fv][ou]rst.*rhyn.*kr[a-z]*\b': 'drie geestelyke keurvorst mitsgaders bij de opperrhynsche nederrhynsche en westphaalsche kreitzen',
    r'\bdrossaa?rdt?\b': 'drossaard',
    r'drossa[a-z]*[dt]\b': 'drossaard',
    r'drossaard': 'drost',
    r'druker\b': 'drukker',
    r'√©': 'e',
    r'e(ij|y)': 'ei',
    r'eygena[ae]rs?': 'eigenaar',
    r'^ *e[yi]lan[a-z]*\b': 'eiland',
    r'eyland': 'eiland',
    r'elue': 'elve',
    r'[&]': 'en',
    r'\bende\b': 'en',
    r'engelan[dt]*': 'engeland',
    r'envoy[a-z]*\b': 'envoyé',
    r'\benvo[ijy][a-z]*\b': 'envoye',
    r'(en *)?\bvoye\b': 'envoye',
    r'erff': 'erf',
    r'\berust\b': 'ernst',
    r'extie': 'excellentie',
    r'\bexs\b': 'extraordinaris',
    r'\be.trao[a-z]*\b': 'extraordinaris',
    r'\be.traordi[a-z]*\b': 'extraordinaris',
    r'\bexts\b': 'extraordinaris',
    r'\bex\b': 'extraordinaris',
    r'majesteit *extraordinaris *([a-z]+)\b': r'extraordinaris \1 van de koning',
    r'ambas[a-z]*\b *ext[a-z]*\b': 'extraordinaris ambassadeur',
    r'\b ex env': 'extraordinaris env',
    r'\be?x[a-z]* *ord[a-z]*\b *envo[a-z]*\b': 'extraordinaris envoye',
    r'fiscael': 'fiscaal',
    r'[fv]ran[ck]*r(y|ij)?c?k?': 'frankrijk',
    r'[fv]ran[ck]+r[a-z]*\b': 'frankrijk',
    r'fransch': 'frans',
    r'friesheim': 'friesheym',
    r'\bf\.? *d\w*\.?': 'furstelijke doorluchtigheid',
    r'gh': 'g',
    r'\bgua': 'ga',
    r'geallieerd\b *$': 'geallieerden',
    r'gedaeg': 'gedaag',
    r'gedepde': 'gedeputeerde',
    r'gedept?(dt?en?)?[.]?\b': 'gedeputeerden',
    r'\bgede\b': 'gedeputeerden',
    r'\bgnael\b': 'generaal',
    r'generael': 'generaal',
    r'generaals': 'generaal',
    r'generaal der\b': 'generaal van de',
    r'general[a-z]*\b *ree?c?k?en[kc]a[a-z]*\b': 'generaliteits-rekenkamer',
    r'gou[td]smi[dt]': 'goudsmidt',
    r'gouuerneur': 'gouverneur',
    r'gouverneur van [a-z]*\b': 'gouverneur',
    r'gouverneur der stadt?': 'gouverneur van',
    r'\bgra[ae]*[fvu]+e?\b': 'graaf',
    r'\bgra[ae]*[fvu]+en\b': 'graven',
    r'\bgra[ae]*[fvu]+in+e?\b': 'gravin',
    r'\bheere? graaf': 'graaf',
    r'\bgraaf *sand[a-z]*\b': 'gravesande',
    r'\bgr.{0,2}f+\w{0,2}r\b': 'griffier',
    r'\briffier': 'griffier',
    r'groot.*br[ei]tt?a[a-z]*\b': 'groot-brittannië',
    r'groot.{0,3}brit[a-z]*\b': 'groot-brittannië',
    r'haa?e?re? *ho\w*:? *mo\w*:?': 'haar hoog mogende',
    r'\bho\w*:? *mo\w*:?': 'hoog mogende',
    r'\bha[ea]?re?n?\b': 'haare',
    r'harden?ste[iy]n': 'hardestein',
    r'h[ae]rto[chg]+e?\b': 'hertog',
    r'\b[a-z]*[hh]ertogenb[a-z]*\b': 'hertogenbosch',
    r'\bheuft\b': 'hoeuft',
    r'\bhoff\b': 'hof',
    r'hollant': 'holland',
    r'^ *mo\b': 'hoog mogende',
    r'hoo(ch|g)h?e[iy]+[dt]+\b': 'hoogheid',
    r'\b in baron van\b': 'in de barronie van',
    r'goede inge': 'inge',
    r'inge[sz]ee?tene': 'ingesetene',
    r'ische co[a-z]*': 'ische compagnie',
    r'jaarig': 'jarig',
    r'\bj\.?l\.?\b': 'jongstleden',
    r'joodt?sche?n?\b': 'joodsche',
    r'ck': 'k',
    r'\b[kc]+a+mere?n?': 'kamer',
    r'kamerlink\b': 'kamerling',
    r'\b[kc]api?[tn]\w*': 'kapitein',
    r'\b[kc]atholi\w*e': 'katholieke',
    r'^ *zyne k[ae][ijy]*[sz]erl(y|ij)c?ke maje[a-z]*': 'keizer',
    r'\bke[ijy]*[sz]er': 'keizer',
    r'zyne keizerl.* maj[a-z]*\b': 'keizer',
    r'\bke[iyj][a-z]*\b *maj?t?[a-z]*\b': 'keizer',
    r'(zyne? *)?keiserly[a-z]*\b *majesteyt': 'keizer',
    r'haare keizerl[a-z]* *maj[a-z]*\b': 'keizerin',
    r'\bke[ijy]+[sz]erl\w*en?\b': 'keizerlijke',
    r'\bke[ijy]+[sz]erl\w*': 'keizerlijk',
    r'\b(keulen|co?eu?len|coln|coeln|c√∂ln|co?eulen|k√∂le?n)\b': 'keulen',
    r'\bc\.? *f\.? *d\.?\b': 'keurvorst',
    r'\b[kch]+[oeur]+[fv][uo]rst': 'keurvorst',
    r'churf[a-z]*\b( *doorl[a-z]*\b)?:?\.?': 'keurvorst',
    r'ch[a-z]*f[a-z]* *hooc?h?g?[a-z]*\b *': 'keurvorst',
    r'churvorstel[a-z]* *doorl[a-z]*\b *': 'keurvorst',
    r'che?ur *[fv]+[a-z]*\b': 'keurvorst',
    r'\b(pf?alt?z.*churfurst|churfurst.*ph?f?alt?s?z[a-z]*\b)': 'keurvorst van de paltz',
    r'\bconin': 'konin',
    r'\b[kc]oninc?g?k?h?x?\b': 'koning',
    r'\b[kc]o?n[a-z]*\b *maj?t[a-z]*\b': 'koning',
    r'z.{0,2}ne? *majesteit': 'koning',
    r'zijn excie': 'excellentie',
    r'\bco\b': 'koning',
    r'\bcon?:?.?\b *van': 'koning van',
    r'\bco van\b': 'koning van',
    r'majesteit *van': 'koning van',
    r'[kc]roone? van': 'koning van',
    r'konings\b *van': 'koning van',
    r'koning van den?e *ma.?.?ke.?n?\b': 'koning van denemarken',
    r'koningh?van': 'koningh van',
    r'haare majes[a-z]*\b den? koningin': 'koningin',
    r'\b[kc]onin[a-z]*in(ne)?\b': 'koningin',
    r'koninc?klijc?k': 'koninklijk',
    r'[kc]oninc?g?k?h?x?l[a-z]*\b': 'koninklijke',
    r'koninglyc?ke': 'koninklijke',
    r'coe?n? *ma[a-z]*\b': 'koninklijke majesteit',
    r'coop': 'koop',
    r'kooplieden': 'koopman',
    r'kreitz': 'kreytz',
    r"\bl' *": "l'",
    r'leeuwar\b': 'leeuwarden',
    r'\blt\b': 'lieutenant',
    r'\blieu[a-z]*\b *- *col?lo[a-z]*\b]\b': 'lieutenant-collonel',
    r'\blieu[a-z]*\b *- *gen[a-z]*]\b': 'lieutenant-generaal',
    r'\blt *-? *generaal\b': 'lieutenant-generaal',
    r'lottharingen': 'lotharingen',
    r'\blu[yij]+c?k\b': 'luik',
    r'mae?rsch[a-z]*\b': 'maarschalk',
    r'ma[ae]stri(ch|g)t': 'maastricht',
    r'\bma[jt]\b': 'majesteit',
    r'\bma\b': 'majesteit',
    r'\bmaj?t\b': 'majesteyt',
    r'\bmr\b': 'meester',
    r'mr\b': 'meester',
    r'meyer': 'meijer',
    r'\b[mm]e[jgy]e[nr][iy]?e': 'meyerye',
    r'[mm][il]+[tr]ai?re': 'militaire',
    r'milita[treni]+e': 'militaire',
    r'mogendeenvoy': 'mogende envoy',
    r'moscouien': 'moscovien',
    r'naem': 'naam',
    r'naght': 'nacht',
    r'nassauw': 'nassau',
    r'nee?der *-? *saxischen': 'nedersaxischen',
    r'oly?i?j?s?can': 'olican',
    r'bis+ch\w*p\b':"bisschop",
    r'\bontfr\w*': 'ontfanger',
    r'\bontfa\w*': 'ontfanger',
    r'oostenryk': 'oostenryck',
    r'o+st.{0,2} *ind\w*': 'oostindische',
    r'\bop[dt]e\b': 'op de',
    r'\borai?g?n?g?j?en?\b': 'oragne',
    r'orangie': 'oragne',
    r'ooue': 'ove',
    r'plenipot[a-z]*\b': 'plenipotentiaris',
    r'poolen': 'polen',
    r'\bpo+rt.ga\w*\b': 'portugal',
    r'[pp]ortuga[ae]?l': 'portugal',
    r'\bpree?sideerende\b': 'praesiderende',
    r'\bpr[ae]+di[ck][ah]\w*': 'predicant',
    r'\bprins\b': 'prince',
    r'prince *(en)? *bisschop *van *luyc?k': 'prince en bisschop van luyk',
    r'prince\b': 'prins',
    r'provintie': 'provincie',
    r'\bpruyss': 'pruiss',
    r'\bpu[iy][sz]ieu[a-z]*\b': 'puisieulx',
    r'\bpi?j?e?y?pers\b': 'pypers',
    r'quartier *schout': 'quartierschout',
    r'ra[ae](d|t)+': 'raad',
    r'raadt?-? *pension': 'raadpension',
    r'raaden': 'raden',
    r'rentemr': 'rentmeester',
    r'repr[ae]*sentant(en)?': 'representant',
    r'republi[a-z]*\b': 'republicq',
    r'resident (te|aan|tot|van)': 'resident van',
    r'rye': 'rie',
    r'roseboom': 'rosenboom',
    r'\brosen,* *boom': 'rosenboom',
    r'\broi\b': 'roy',
    r'ruslandt?': 'rusland',
    r'\bsas.*burg': 'sasburg',
    r's[ce][hbdn]a[pb]\b': 'schap',
    r'schen\b': 'sche',
    r'schepenen': 'schepen',
    r'schee?pene?n?': 'schepen',
    r'schepen (der|tot)': 'schepen van',
    r'schoolmrs?': 'schoolmeester',
    r'\bsc?h?w[ae]*rt?z?s?h?enb[oe][a-z]*\b': 'schwartzenbergh',
    r'\bslants\b': 'slandts',
    r'siminia': 'sminia',
    r'soldaet': 'soldaat',
    r'soldaten': 'soldaat',
    r'sommelsd[a-z]*\b': 'sommelsdyck',
    r'\bspaen\b': 'spaan',
    r'spaanschen': 'spaansche',
    r'spaignaerts': 'spaignaerden',
    r'\bspai?g?nj?i?en?\b': 'spaigne',
    r'stadhouder': 'stadthouder',
    r'substituyt': 'substitut',
    r'swerius': 'suerius',
    r'supplts\b': 'suppliants',
    r'sweden': 'sweeden',
    r'swee[dt]+sch': 'sweedsch',
    r'swee[dt]schen?': 'sweedsche',
    r'\btotte': 'tot de',
    r'\btottet': 'tot het',
    r'\btur[ckx].*eize[a-z]*\b': 'turkse keizer',
    r'u(ij|y)+': 'ui',
    r'\buyt\b': 'uit',
    r'uij': 'uy',
    r'\bva\b': 'van',
    r'alsvan': 'van',
    r'\bvna\b': 'van',
    r'\bvande': 'van de',
    r'van de[sn] *sel[vf]\w*': 'van de',
    r'van beyde de': 'van de beide',
    r'van *de[rn]? *capp?el[a-z]*\b': 'van de capelle',
    r'\b(by|van) *dee?[zs]?e?n? *sta[ea]t\b': 'van desen staat',
    r'van de?[sz]?en? sta[ae]t': 'van desen staat',
    r'van de[a-z]* land(e)': 'van deser landen',
    r"\bvan[']?t\b": 'van het',
    r've[iy]lgeld': 'veilgeld',
    r'veld?t? *maarschalk': 'veldmaarschalk',
    r',? *veld?t?-? ?maarsch[a-z]*\b *(van *de?e?[sz]?en *sta[ae]t *)?$': 'veldmaarschalk van deze staat',
    r'veltman': 'veldman',
    r'verhoogh?de': 'verhoogde',
    r'vice-+': 'vice-',
    r'vlaendenen': 'vlaenderen',
    r'\b[fv]loot\b': 'vloote',
    r'voocht': 'voogd',
    r'voogden': 'voogd',
    r'furst': 'vorst',
    r'\bvorstel[a-z]* *doorl[a-z]*\b *': 'vorst',
    r'\bf\.\b': 'vorstelijke',
    r'vranc?k?ri?j?y?c?k': 'vrankryck',
    r'vr[a-z]*bergen?\b': 'vrybergen',
    r'waldeck': 'waldecq',
    r'wassenaer': 'wassenaar',
    r'weduwe van [a-z]*\b': 'weduwe',
    r'weesmeesteren': 'weesmeester',
    r'wost': 'west',
    r'\b[ww]est.?.?.?ind': 'west-ind',
    r'wo.?.?nend?n?e? (tot|op|in|te)\b': 'woonachtig in',
    r'inwoond?er van': 'woonachtig in',
    r'woonende [a-z]*\b': 'woonachtig in',
    r'woonachtig [a-z]*\b': 'woonachtig in',
    r'\b(y|ij?)ss?elm[a-z]*\b': 'ysselmuyden',
    r'[szsfz]a[ae]?[ce]?ke?n?\b': 'zaken',
    r'\b[zs](ij|y)ne?n?e?r?\b': 'zijn',
    r'\b[zs]+(ij|y)+[un]+e?n?s?r?\b': 'zijn',
    r'\b[yz]+n\b': 'zijn',
    r'soelen': 'zoelen',
    r'\bswits': 'zwits',
    r'van *de\w{0,2}\b': 'van de',
    r'heer de\w\b': 'heer de',
}
