substitutions = {
    " ' s ": " 's ",
    " s *' ": " 's ",
    '': '',
    ' *[-‚Äî] *': '-',
    '-+': '-',
    ',,?,': ',',
    ' +,': ',',
    ' *\\bende\\b *': ', ',
    " ' +": "'",
    'den *bosch': "'s hertogenbosch",
    'van den lande': "'s lands",
    '(burger|inwoner|burgemeester) *der stadt': "r'\\1 van de stad'",
    '‚àö¬©': 'é',
    '‚Äö√†√∂¬¨¬©': 'é',
    'ae': 'aa',
    '\\baen\\b': 'aan',
    "\\ba[ae]n *t'?\\b": 'aan het',
    '(a?a|e)rt[sz] *h[ae]rto[a-z]*\\b': 'aartshertog',
    'admirael': 'admiraal',
    'adm[a-z]*r[a-z]*l[a-z]\\b': 'admiraal',
    'admiraliteyt': 'admiraliteit',
    'adm[a-z]*r[a-z]*l[a-z]*t[a-z]*\\b': 'admiraliteit',
    'advocaet': 'advocaat',
    'advocaten': 'advocaat',
    'aff?geson *$': 'affgesonden',
    'aff?ge[sz]anten?': 'afgezante',
    'geboo?ren *(te|in|van)\\b': 'afkomstig uit',
    'geboorti(ch|g) (uit|van|in)': 'afkomstig uit',
    'agent tot [a-z]*\\b': 'agent',
    '\\bamm? *anu[a-z]*\\b': 'amanuensis',
    'am *bassadeur': 'ambassadeur',
    '\\bambr[a-z]*\\b': 'ambassadeur',
    'ambassade\\b': 'ambassadeur',
    'ambassadeur *des *koning': 'ambassadeur van de koning',
    'baclouch': 'bachlouch',
    '\\bbai?l[ij]\\w*\\b': 'bailliu',
    'bailliu der stadt': 'bailliu van',
    '\\bd?l?en? *baron': 'baron',
    '\\bbaroe?n?n[ijvy*]?e?n?\\b': 'baron',
    '\\bbaron de\\b': 'baron van',
    "\\bbaron *d'": 'baron van ',
    '\\bvrouwe *baron?nesse\\b': 'baronnesse',
    'bergen.*zoom\\b': 'bergen op zoom',
    'berkenrode': 'berkenroode',
    'bewaer': 'bewaar',
    'bewin[a-z]*bber(en|s)?': 'bewindhebber',
    'beijeren': 'beyeren',
    '\\bby\\b': 'bij',
    'bondge[ncvr][oc]+[d tr]': 'bondgenoot',
    '\\bbonen\\b': 'boonen',
    'braban[dt]\\b': 'brabandt',
    '\\bbran[a-z]*b[ou]r(ch|g)[a-z]*\\b': 'brandenburg',
    'brouc?k?h?\\b': 'broeck',
    'broek': 'broeck',
    '\\bbruijn *nincx': 'bruijnincx',
    'brui?j?y?ninc?x': 'bruyninx',
    'burch\\b': 'burg',
    'burgh$': 'burg',
    'b[uo]rc?k?g?h?\\b': 'burg',
    'b[ou]rger? *meester': 'burgemeester',
    '\\bb[uo]r(ch|g)h?er\\b': 'burger',
    'burger tot?': 'burger van',
    '\\bcaan\\b': 'caen',
    'canonik': 'canonicq',
    '\\b[ck]api?t[a-z]*n\\b': 'capiteyn',
    '\\bcat\\b': 'cats',
    'gt': 'cht',
    '\\b(brandenburg.*keurvorst|keurvorst.*brandenburg\\b)': 'churfurst van brandenburg',
    'cheurvorst': 'churvorst',
    'churvorst *van': 'churvorst van',
    'churf[a-z]*\\b': 'churvorstelijk',
    'colijer': 'coljer',
    'collator der': 'collator van de',
    '\\bcoll?onn?el\\b': 'collonel',
    'commande[a-z]*\\b': 'commandant',
    '\\bcommaa?n?d(an|eu)[a-z]*\\b': 'commandant',
    'commandant (te|tot)': 'commandant van',
    'commmandant der stadt': 'commandant van',
    'commandant der': 'commandant van de',
    'commandant officier': 'commanderende officier',
    'commandee?r[a-z]*\\b (tot|der stad)': 'commandeur van',
    'commissarisen': 'commissarissen',
    '\\b[cc]ompe?[.]?\\b': 'compagnie',
    'comp[nr]?i?e': 'compagnie',
    'compaignie': 'compagnie',
    'consul tot': 'consul te',
    'contr[ae]rolleur': 'controlleur',
    'conuoy': 'convoy',
    'czaer': 'czaar',
    '\\bzaarsche': 'czaarsche',
    "d' *": "d'",
    '\\bde *raaf\\b': 'de graaf',
    "d'hee": 'de hee',
    'dezaken': 'de zaken',
    'dee?nn?emar[a-z]*\\b': 'denemarken',
    'den[a-z]*marken': 'denemarken',
    'der sta\\b': 'der stadt',
    '\\bdee?[sz]er? *land[a-z]*\\b': 'dezer lande',
    '\\bdoorlu[a-z]*\\b': 'doorluchtigheid',
    '\\bdl?t\\b': 'doorluchtigheid',
    'doorlt\\b': 'doorluchtigheid',
    'drie.*geest.*[fv][ou]rst.*rhyn.*kr[a-z]*\\b': 'drie geestelyke keurvorst mitsgaders bij de opperrhynsche nederrhynsche en westphaalsche kreitzen',
    '\\bdrossaa?rdt?\\b': 'drossaard',
    'drossa[a-z]*[dt]\\b': 'drossaard',
    'drossaard': 'drost',
    'druker\\b': 'drukker',
    '√©': 'e',
    'e(ij|y)': 'ei',
    'eygena[ae]rs?': 'eigenaar',
    '^ *e[yi]lan[a-z]*\\b': 'eiland',
    'eyland': 'eiland',
    'elue': 'elve',
    '[&]': 'en',
    '\\bende\\b': 'en',
    'engelan[dt]*': 'engeland',
    'envoy[a-z]*\\b': 'envoyé',
    '\\benvo[ijy][a-z]*\\b': 'envoye',
    '(en *)?\\bvoye\\b': 'envoye',
    'erff': 'erf',
    '\\berust\\b': 'ernst',
    'extie': 'excellentie',
    '\\bexs\\b': 'extraordinaris',
    '\\be.trao[a-z]*\\b': 'extraordinaris',
    '\\be.traordi[a-z]*\\b': 'extraordinaris',
    '\\bexts\\b': 'extraordinaris',
    '\\bex\\b': 'extraordinaris',
    'majesteit *extraordinaris *([a-z]+)\\b': 'extraordinaris \x01 van de koning',
    'ambas[a-z]*\\b *ext[a-z]*\\b': 'extraordinaris ambassadeur',
    '\\b ex env': 'extraordinaris env',
    '\\be?x[a-z]* *ord[a-z]*\\b *envo[a-z]*\\b': 'extraordinaris envoye',
    'fiscael': 'fiscaal',
    '[fv]ran[ck]* *r(y|ij)?c?k?': 'frankrijk',
    '[fv]ran[ck]+ *r[a-z]*\\b': 'frankrijk',
    'fransch': 'frans',
    'friesheim': 'friesheym',
    '\\bf\\.? *d\\w*\\.?': 'furstelijke doorluchtigheid',
    'gh': 'g',
    '\\bgua': 'ga',
    'geallieerd\\b *$': 'geallieerden',
    'gedaeg': 'gedaag',
    'gedepde': 'gedeputeerde',
    'gedept?(dt?en?)?[.]?\\b': 'gedeputeerden',
    '\\bgede\\b': 'gedeputeerden',
    '\\bgnael\\b': 'generaal',
    'generael': 'generaal',
    'generaals': 'generaal',
    'generaal der\\b': 'generaal van de',
    'general[a-z]*\\b *ree?c?k?en[kc]a[a-z]*\\b': 'generaliteits-rekenkamer',
    'gou[td]smi[dt]': 'goudsmidt',
    'gouuerneur': 'gouverneur',
    'gouverneur van [a-z]*\\b': 'gouverneur',
    'gouverneur der stadt?': 'gouverneur van',
    '\\bgra[ae]*[fvu]+e?\\b': 'graaf',
    '\\bgra[ae]*[fvu]+en\\b': 'graven',
    '\\bgra[ae]*[fvu]+in+e?\\b': 'gravin',
    '\\bheere? graaf': 'graaf',
    '\\bgraaf *sand[a-z]*\\b': 'gravesande',
    '\\bgr.{0,2}f+\\w{0,2}r\\b': 'griffier',
    '\\briffier': 'griffier',
    'groot.*br[ei]tt?a[a-z]*\\b': 'groot-brittannië',
    'groot.{0,3}brit[a-z]*\\b': 'groot-brittannië',
    'haa?e?re? *ho\\w*:? *mo\\w*:?': 'haar hoog mogende',
    '\\bho\\w*:? *mo\\w*:?': 'hoog mogende',
    '\\bha[ea]?re?n?\\b': 'haare',
    'harden?ste[iy]n': 'hardestein',
    'h[ae]rto[chg]+e?\\b': 'hertog',
    '\\b[a-z]*[hh]ertogenb[a-z]*\\\\b': 'hertogenbosch',
    '\\bheuft\\b': 'hoeuft',
    '\\bhoff\\b': 'hof',
    'hollant': 'holland',
    '^ *mo\\b': 'hoog mogende',
    'hoo(ch|g)h?e[iy]+[dt]+\\b': 'hoogheid',
    '\\b in baron van\\b': 'in de barronie van',
    'goede inge': 'inge',
    'inge[sz]ee?tene': 'ingesetene',
    'ische co[a-z]*': 'ische compagnie',
    'jaarig': 'jarig',
    '\\bj\\.?l\\.?\\b': 'jongstleden',
    'joodt?sche?n?\\b': 'joodsche',
    'ck': 'k',
    '\\b[kc]+a+mere?n?': 'kamer',
    'kamerlink\\b': 'kamerling',
    '\\b[kc]api?[tn]\\w*': 'kapitein',
    '\\b[kc]atholi\\w*e': 'katholieke',
    '^ *zyne k[ae][ijy]*[sz]erl(y|ij)c?ke maje[a-z]*': 'keizer',
    '\\bke[ijy]*[sz]er': 'keizer',
    'zyne keizerl.* maj[a-z]*\\b': 'keizer',
    '\\bke[iyj][a-z]*\\b *maj?t?[a-z]*\\b': 'keizer',
    '(zyne? *)?keiserly[a-z]*\\b *majesteyt': 'keizer',
    'haare keizerl[a-z]* *maj[a-z]*\\b': 'keizerin',
    '\\bke[ijy]+[sz]erl\\w*en?\\b': 'keizerlijke',
    '\\bke[ijy]+[sz]erl\\w*': 'keizerlijk',
    '\\b(keulen|co?eu?len|coln|coeln|c√∂ln|co?eulen|k√∂le?n)\\b': 'keulen',
    '\\bc\\.? *f\\.? *d\\.?\\b': 'keurvorst',
    '\\b[kch]+[oeur]+[fv][uo]rst': 'keurvorst',
    'churf[a-z]*\\b( *doorl[a-z]*\\b)?:?\\.?': 'keurvorst',
    'ch[a-z]*f[a-z]* *hooc?h?g?[a-z]*\\b *': 'keurvorst',
    'churvorstel[a-z]* *doorl[a-z]*\\b *': 'keurvorst',
    'che?ur *[fv]+[a-z]*\\b': 'keurvorst',
    '\\b(pf?alt?z.*churfurst|churfurst.*ph?f?alt?s?z[a-z]*\\b)': 'keurvorst van de paltz',
    '\\bconin': 'konin',
    '\\b[kc]oninc?g?k?h?x?\\b': 'koning',
    '\\b[kc]o?n[a-z]*\\b *maj?t[a-z]*\\b': 'koning',
    'z.{0,2}ne? *majesteit': 'koning',
    'zijn excie': 'excellentie',
    '\\bco\\b': 'koning',
    '\\bcon?:?.?\\b *van': 'koning van',
    '\\bco van\\b': 'koning van',
    'majesteit *van': 'koning van',
    '[kc]roone? van': 'koning van',
    'konings\\b *van': 'koning van',
    'koning van den?e *ma.?.?ke.?n?\\b': 'koning van denemarken',
    'koningh?van': 'koningh van',
    'haare majes[a-z]*\\b den? koningin': 'koningin',
    '\\b[kc]onin[a-z]*in(ne)?\\b': 'koningin',
    'koninc?klijc?k': 'koninklijk',
    '[kc]oninc?g?k?h?x?l[a-z]*\\b': 'koninklijke',
    'koninglyc?ke': 'koninklijke',
    'coe?n? *ma[a-z]*\\b': 'koninklijke majesteit',
    'coop': 'koop',
    'kooplieden': 'koopman',
    'kreitz': 'kreytz',
    "\\bl' *": "l'",
    'leeuwar\\b': 'leeuwarden',
    '\\blt\\b': 'lieutenant',
    '\\blieu[a-z]*\\b *- *col?lo[a-z]*\\b]\\b': 'lieutenant-collonel',
    '\\blieu[a-z]*\\b *- *gen[a-z]*]\\b': 'lieutenant-generaal',
    '\\blt *-? *generaal\\b': 'lieutenant-generaal',
    'lottharingen': 'lotharingen',
    '\\blu[yij]+c?k\\b': 'luik',
    'mae?rsch[a-z]*\\b': 'maarschalk',
    'ma[ae]stri(ch|g)t': 'maastricht',
    '\\bma[jt]\\b': 'majesteit',
    '\\bma\\b': 'majesteit',
    '\\bmaj?t\\b': 'majesteyt',
    '\\bmr\\b': 'meester',
    'mr\\b': 'meester',
    'meyer': 'meijer',
    '\\b[mm]e[jgy]e[nr][iy]?e': 'meyerye',
    '[mm][il]+[tr]ai?re': 'militaire',
    'milita[treni]+e': 'militaire',
    'mogendeenvoy': 'mogende envoy',
    'moscouien': 'moscovien',
    'naem': 'naam',
    'naght': 'nacht',
    'nassauw': 'nassau',
    'nee?der *-? *saxischen': 'nedersaxischen',
    'oly?i?j?s?can': 'olican',
    'bis+ch\\w*p\\b':"bisschop",
    '\\bontfr\\w*': 'ontfanger',
    '\\bontfa\\w*': 'ontfanger',
    'oostenryk': 'oostenryck',
    'o+st.{0,2} *ind\\w*': 'oostindische',
    '\\bop[dt]e\\b': 'op de',
    '\\borai?g?n?g?j?en?\\b': 'oragne',
    'orangie': 'oragne',
    'ooue': 'ove',
    'plenipot[a-z]*\\b': 'plenipotentiaris',
    'poolen': 'polen',
    '\\bpo+rt.ga\\w*\\b': 'portugal',
    '[pp]ortuga[ae]?l': 'portugal',
    '\\bpree?sideerende\\b': 'praesiderende',
    '\\bpr[ae]+di[ck][ah]\\w*': 'predicant',
    '\\bprins\\b': 'prince',
    'prince *(en)? *bisschop *van *luyc?k': 'prince en bisschop van luyk',
    'prince\\b': 'prins',
    'provintie': 'provincie',
    '\\bpruyss': 'pruiss',
    '\\bpu[iy][sz]ieu[a-z]*\\b': 'puisieulx',
    '\\bpi?j?e?y?pers\\b': 'pypers',
    'quartier *schout': 'quartierschout',
    'ra[ae](d|t)+': 'raad',
    'raadt?-? *pension': 'raadpension',
    'raaden': 'raden',
    'rentemr': 'rentmeester',
    'repr[ae]*sentant(en)?': 'representant',
    'republi[a-z]*\\b': 'republicq',
    'resident [^van]*.*$': 'resident',
    'resident (te|aan|tot|van)': 'resident van',
    'rye': 'rie',
    'roseboom': 'rosenboom',
    '\\brosen,* *boom': 'rosenboom',
    '\\broi\\b': 'roy',
    'ruslandt?': 'rusland',
    '\\bsas.*burg': 'sasburg',
    's[ce][hbdn]a[pb]\\\\b': 'schap',
    'schen\\b': 'sche',
    'schepenen': 'schepen',
    'schee?pene?n?': 'schepen',
    'schepen (der|tot)': 'schepen van',
    'schoolmrs?': 'schoolmeester',
    '\\bsc?h?w[ae]*rt?z?s?h?enb[oe][a-z]*\\b': 'schwartzenbergh',
    '\\bslants\\b': 'slandts',
    'siminia': 'sminia',
    'soldaet': 'soldaat',
    'soldaten': 'soldaat',
    'sommelsd[a-z]*\\b': 'sommelsdyck',
    '\\bspaen\\b': 'spaan',
    'spaanschen': 'spaansche',
    'spaignaerts': 'spaignaerden',
    '\\bspai?g?nj?i?en?\\b': 'spaigne',
    'stadhouder': 'stadthouder',
    'substituyt': 'substitut',
    'swerius': 'suerius',
    'supplts\\b': 'suppliants',
    'sweden': 'sweeden',
    'swee[dt]+sch': 'sweedsch',
    'swee[dt]schen?': 'sweedsche',
    '\\btotte': 'tot de',
    '\\btottet': 'tot het',
    '\\btur[ckx].*eize[a-z]*\\b': 'turkse keizer',
    'u(ij|y)+': 'ui',
    '\\buyt\\b': 'uit',
    'uij': 'uy',
    '\\bva\\b': 'van',
    'alsvan': 'van',
    '\\bvna\\b': 'van',
    '\\bvande': 'van de',
    'van de[sn] *sel[vf]\\w*': 'van de',
    'van beyde de': 'van de beide',
    'van *de[rn]? *capp?el[a-z]*\\b': 'van de capelle',
    'vanden': 'van den',
    'vander': 'van der',
    '\\b(by|van) *dee?[zs]?e?n? *sta[ea]t\\b': 'van desen staat',
    'van de?[sz]?en? sta[ae]t': 'van desen staat',
    'van de[a-z]* land(e)': 'van deser landen',
    "\\bvan[']?t\\b": 'van het',
    've[iy]lgeld': 'veilgeld',
    'veld?t? *maarschalk': 'veldmaarschalk',
    ',? *veld?t?-? ?maarsch[a-z]*\\b *(van *de?e?[sz]?en *sta[ae]t *)?$': 'veldmaarschalk van deze staat',
    'veltman': 'veldman',
    'verhoogh?de': 'verhoogde',
    'vice-+': 'vice-',
    'vlaendenen': 'vlaenderen',
    '\\b[fv]loot\\b': 'vloote',
    'voocht': 'voogd',
    'voogden': 'voogd',
    'furst': 'vorst',
    '\\bvorstel[a-z]* *doorl[a-z]*\\b *': 'vorst',
    '\\bf\\.\\b': 'vorstelijke',
    'vr[a-z]*bergen?\\b': 'vrybergen',
    'waldeck': 'waldecq',
    'wassenaer': 'wassenaar',
    'weduwe van [a-z]*\\b': 'weduwe',
    'weesmeesteren': 'weesmeester',
    'wost': 'west',
    '\\b[ww]est.?.?.?ind': 'west-ind',
    'wo.?.?nend?n?e? (tot|op|in|te)\\b': 'woonachtig in',
    'inwoond?er van': 'woonachtig in',
    'woonende [a-z]*\\b': 'woonachtig in',
    'woonachtig [a-z]*\\b': 'woonachtig in',
    '\\b(y|ij?)ss?elm[a-z]*\\b': 'ysselmuyden',
    '[szsfz]a[ae]?[ce]?ke?n?\\b': 'zaken',
    '\\b[zs](ij|y)ne?n?e?r?\\b': 'zijn',
    '\\b[zs]+(ij|y)+[un]+e?n?s?r?\\b': 'zijn',
    '\\b[yz]+n\\b': 'zijn',
    'soelen': 'zoelen',
    '\\bswits': 'zwits',
}
