version: '3.8'

services:

  importer:
    container_name: importer
    build: .
    volumes:
      - ./tmp:/pim-tr-import/tmp
      - ./types.csv:/pim-tr-import/types.csv
      - ./external-identifiers.csv:/pim-tr-import/external-identifiers.csv
      - ./import.log:/pim-tr-import/import.log
    environment:
      GOOGLE_AUTHORIZATION: ${GOOGLE_AUTHORIZATION}
      NODE_OPTIONS: '--max_old_space_size=4096'
      PIM: 'https://images.diginfra.net'
      SUBSET_CSV: './external-identifiers.csv'
      TMP: './tmp'
      TR: 'http://tr_textrepo:8080'
      TYPE_CSV: './types.csv'
      CACHE: 250 # PIM files (buffer PIM json files, that can contain multiple TR files, each with a different type)
    command: ./import.sh
    networks:
      - textrepo_network

networks:
  textrepo_network:
    external: true
    name: textrepo_network
